# Generated by Django 4.2.1 on 2025-05-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sudoku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_attempted", models.DateTimeField(blank=True, null=True)),
                ("puzzle", models.BinaryField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "canonical_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("solves", models.PositiveIntegerField(default=0)),
                ("total_time", models.PositiveIntegerField(default=0)),
                ("average_time", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sudokus_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="sudokus", to="sudoku.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSudokuStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("best_time", models.PositiveIntegerField(default=0)),
                ("last_time", models.PositiveIntegerField(default=0)),
                ("first_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("date_solved", models.DateTimeField(blank=True, null=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "sudoku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stats",
                        to="sudoku.sudoku",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sudoku_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "sudoku")},
            },
        ),
    ]
