# Generated by Django 5.2.1 on 2025-05-24 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('puzzle', models.BinaryField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('canonical_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('solves', models.PositiveIntegerField(default=0)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('average_time', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sudokus_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='sudokus', to='sudoku.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserSudokuFinished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('sudoku_id', models.PositiveIntegerField()),
                ('saved_board_state', models.BinaryField(blank=True, null=True)),
                ('attempts_to_solve', models.PositiveIntegerField(default=1)),
                ('completion_time', models.PositiveIntegerField()),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user_id', 'completed_at'], name='sudoku_user_user_id_e36288_idx'), models.Index(fields=['sudoku_id', 'completion_time'], name='sudoku_user_sudoku__624af6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSudokuOngoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('sudoku_id', models.PositiveIntegerField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('current_time', models.PositiveIntegerField(default=0)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('first_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('saved_board_state', models.BinaryField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('user_id', 'sudoku_id')},
            },
        ),
    ]
