# Generated by Django 5.2 on 2025-04-20 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sudoku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("solves", models.PositiveIntegerField(default=0)),
                (
                    "total_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Total seconds spent solving"
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSudokuStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Best time in seconds"
                    ),
                ),
                (
                    "sudoku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sudoku.sudoku"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "sudoku")},
            },
        ),
    ]
