# Generated by Django 5.2 on 2025-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedleaderboardentry",
            name="rank",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
