# Generated by Django 5.2 on 2025-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sudoku",
            name="rating",
        ),
        migrations.AddField(
            model_name="usersudokustats",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersudokustats",
            name="date_solved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersudokustats",
            name="first_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersudokustats",
            name="last_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sudoku",
            name="total_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usersudokustats",
            name="best_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
