# Generated by Django 4.2.1 on 2025-06-04 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("solved", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
