# Generated by Django 5.2 on 2025-05-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sudoku",
            name="solution_string",
            field=models.TextField(blank=True, null=True),
        ),
    ]
