# Generated by Django 5.2 on 2025-05-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0002_sudoku_solution_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sudoku",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="sudoku",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="sudoku",
            name="average_time",
        ),
        migrations.RemoveField(
            model_name="sudoku",
            name="total_time",
        ),
        migrations.AddField(
            model_name="sudoku",
            name="sum_ratings",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sudoku",
            name="sum_time",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usersudokudone",
            name="sudoku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sudoku_done",
                to="sudoku.sudoku",
            ),
        ),
    ]
