# Generated by Django 4.2.1 on 2025-06-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sudoku", "0002_cachedleaderboardentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedleaderboardentry",
            name="rank",
        ),
    ]
