# Generated by Django 5.2 on 2025-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0003_remove_sudoku_attempts_remove_sudoku_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersudokuongoing",
            name="was_previously_completed",
            field=models.BooleanField(default=False),
        ),
    ]
