# Generated by Django 4.2.1 on 2025-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_tag_sudoku_average_rating_sudoku_average_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='puzzle_string',
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='solution_string',
        ),
        migrations.AddField(
            model_name='sudoku',
            name='puzzle',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
