# Generated by Django 4.2.1 on 2025-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sudoku",
            "0004_remove_sudoku_difficulty_remove_sudoku_puzzle_string_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sudoku",
            name="canonical_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
